


#
#                     ██████╗░░█████╗░░██╗░░░░░░░██╗  ░█████╗░░█████╗░░██████╗███╗░░░███╗███████╗████████╗██╗░█████╗░░██████╗
#                     ██╔══██╗██╔══██╗░██║░░██╗░░██║  ██╔══██╗██╔══██╗██╔════╝████╗░████║██╔════╝╚══██╔══╝██║██╔══██╗██╔════╝
#                     ██████╦╝██║░░██║░╚██╗████╗██╔╝  ██║░░╚═╝██║░░██║╚█████╗░██╔████╔██║█████╗░░░░░██║░░░██║██║░░╚═╝╚█████╗░
#                     ██╔══██╗██║░░██║░░████╔═████║░  ██║░░██╗██║░░██║░╚═══██╗██║╚██╔╝██║██╔══╝░░░░░██║░░░██║██║░░██╗░╚═══██╗
#                     ██████╦╝╚█████╔╝░░╚██╔╝░╚██╔╝░  ╚█████╔╝╚█████╔╝██████╔╝██║░╚═╝░██║███████╗░░░██║░░░██║╚█████╔╝██████╔╝
#                     ╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░░  ░╚════╝░░╚════╝░╚═════╝░╚═╝░░░░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░╚════╝░╚═════╝░



#                                            ▒█▀▀█ █░░█ 　 ▒█░░░ █░░█ ▀▀█▀▀ █▀▀█ ░▀░ █▀▀█ 
#                                            ▒█▀▀▄ █▄▄█ 　 ▒█░░░ █▄▄█ ░░█░░ █▄▄▀ ▀█▀ █▄▄█ 
#                                            ▒█▄▄█ ▄▄▄█ 　 ▒█▄▄█ ▄▄▄█ ░░▀░░ ▀░▀▀ ▀▀▀ ▀░░▀


messages:
   join: "&e[&6!&E] You just joined the &6bow &epractice &6!"
   leave: "&e[&6!&e] You just left the game !"
   ingame: "&e[&6!&e] You are already in this mode &6!"
   iron: "&e[&6!&e] You touched the iron target and won &e250 gold &6!"
   gold: "&e[&6!&e] You touched the Gold target and won &e500 gold &6!"
   diamond: "&e[&6!&e] You touched the Diamond target and won &e1000 gold &6!"
   reload: "&e[&6!&e] You just reloaded the config !"
   cooldownremove: "&e[&6!&e] You just removed your cooldown !"
   store: "&e[&6!&e] &6wwww.exemple.com"
   




#            ┏━━━┓                ┏┓
#            ┃┏━┓┃                ┃┃
#            ┃┃ ┗╋━━┳┓┏┳┓┏┳━━┳━┓┏━┛┣━━┓
#            ┃┃ ┏┫┏┓┃┗┛┃┗┛┃┏┓┃┏┓┫┏┓┃━━┫
#            ┃┗━┛┃┗┛┃┃┃┃┃┃┃┏┓┃┃┃┃┗┛┣━━┃
#            ┗━━━┻━━┻┻┻┻┻┻┻┛┗┻┛┗┻━━┻━━┛
commands:
#All commands are sent by console set %player% to get the player's name
  iron: "eco give %player% 250"
  gold: "eco give %player% 500"
  diamond: "eco give %player% 1000"
   




#               ╭━━╮╭╮        ╭━╮
#               ╰┃┃╯┃╰╮╭━╮╭━━╮┃━┫
#               ╭┃┃╮┃╭┫┃┻┫┃┃┃┃┣━┃
#               ╰━━╯╰━╯╰━╯╰┻┻╯╰━╯
items:
  leave: 
    name: "&4&lLeave"
    lore: "&7Return tu spawn and try again tommorow !"
  buymore:
    name: "&a&lPurshase More arrows"
    lore: "&7Buy more arrows at the store"
  info:
    name: "&eInfo"
    lore: "&7If you buy more arrows wait for them to pop in your inventory"






#               ╭━━━╮     ╭╮
#               ┃╭━╮┃    ╭╯╰╮
#               ┃┃ ┃┃╭━━╮╰╮╭╯╭╮╭━━╮╭━╮ ╭━━╮
#               ┃┃ ┃┃┃╭╮┃ ┃┃ ┣┫┃╭╮┃┃╭╮╮┃━━┫
#               ┃╰━╯┃┃╰╯┃ ┃╰╮┃┃┃╰╯┃┃┃┃┃┣━━┃
#               ╰━━━╯┃╭━╯ ╰━╯╰╯╰━━╯╰╯╰╯╰━━╯
#                    ┃┃
#                    ╰╯
joinloc:
  world:
  y:
  x:
  z:
  #on leave téléport to old position !
oldposloc:
  enabled: false
leaveloc:
  world:
  y:
  x:
  z:
  
  
  
  
  
  
#            ╔═══╗
#            ║╔═╗║
#            ║╚═╝║╔══╗╔═╗╔╗╔╗╔╗╔══╗╔══╗╔╗╔══╗╔═╗─╔══╗
#            ║╔══╝║║═╣║╔╝║╚╝║╠╣║══╣║══╣╠╣║╔╗║║╔╗╗║══╣
#            ║║   ║║═╣║║ ║║║║║║╠══║╠══║║║║╚╝║║║║║╠══║
#            ╚╝   ╚══╝╚╝ ╚╩╩╝╚╝╚══╝╚══╝╚╝╚══╝╚╝╚╝╚══╝

#                       bow.admin


#                              ████████████████████████████████████████
#                              ██████▀░░░░░░░░▀████████▀▀░░░░░░░▀██████
#                              ████▀░░░░░░░░░░░░▀████▀░░░░░░░░░░░░▀████
#                              ██▀░░░░░░░░░░░░░░░░▀▀░░░░░░░░░░░░░░░░▀██
#                              ██░░░░░░░░░░░░░░░░░░░▄▄░░░░░░░░░░░░░░░██
#                              ██░░░░░░░░░░░░░░░░░▄▀░█░░░░░░░░░░░░░░░██    
#                              ██░░░░░░░░░░████▄▄▄▀░░▀▀▀▀▄░░░░░░░░░░░██
#                              ██▄░░░░░░░░░████░░░░░░░░░░█░░░░░░░░░░▄██
#                              ████▄░░░░░░░████░░░░░░░░░░█░░░░░░░░▄████
#                              ██████▄░░░░░████▄▄▄░░░░░░░█░░░░░░▄██████
#                              ████████▄░░░▀▀▀▀░░░▀▀▀▀▀▀▀░░░░░▄████████
#                              ██████████▄░░░░░░░░░░░░░░░░░░▄██████████
#                              ████████████▄░░░░░░░░░░░░░░▄████████████
#                              ██████████████▄░░░░░░░░░░▄██████████████
#                              ████████████████▄░░░░░░▄████████████████
#                              ██████████████████▄▄▄▄██████████████████
#
#██╗░░░░░███████╗░█████╗░██╗░░░██╗███████╗  ░█████╗░  ██████╗░███████╗██╗░░░██╗██╗███████╗░██╗░░░░░░░██╗                                                                                                          
#██║░░░░░██╔════╝██╔══██╗██║░░░██║██╔════╝  ██╔══██╗  ██╔══██╗██╔════╝██║░░░██║██║██╔════╝░██║░░██╗░░██║            
#██║░░░░░█████╗░░███████║╚██╗░██╔╝█████╗░░  ███████║  ██████╔╝█████╗░░╚██╗░██╔╝██║█████╗░░░╚██╗████╗██╔╝            
#██║░░░░░██╔══╝░░██╔══██║░╚████╔╝░██╔══╝░░  ██╔══██║  ██╔══██╗██╔══╝░░░╚████╔╝░██║██╔══╝░░░░████╔═████║░
#███████╗███████╗██║░░██║░░╚██╔╝░░███████╗  ██║░░██║  ██║░░██║███████╗░░╚██╔╝░░██║███████╗░░╚██╔╝░╚██╔╝░   
#╚══════╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝  ╚═╝░░╚═╝  ╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░

#                  ░█████╗░███╗░░██╗  ░██████╗██████╗░██╗░██████╗░░█████╗░████████╗
#                  ██╔══██╗████╗░██║  ██╔════╝██╔══██╗██║██╔════╝░██╔══██╗╚══██╔══╝
#                  ██║░░██║██╔██╗██║  ╚█████╗░██████╔╝██║██║░░██╗░██║░░██║░░░██║░░░
#                  ██║░░██║██║╚████║  ░╚═══██╗██╔═══╝░██║██║░░╚██╗██║░░██║░░░██║░░░
#                  ╚█████╔╝██║░╚███║  ██████╔╝██║░░░░░██║╚██████╔╝╚█████╔╝░░░██║░░░
#                  ░╚════╝░╚═╝░░╚══╝  ╚═════╝░╚═╝░░░░░╚═╝░╚═════╝░░╚════╝░░░░╚═╝░░░                                                                                                             
#